import { ArrowRight, ClockCountdown, Phone, Target, UserPlus, WarningCircle } from "@phosphor-icons/react/dist/ssr";
import Link from "next/link";

import { LifecyclePill } from "@/components/lifecycle-pill";
import type { DailySalesWorkspaceDTO } from "@/types/sales-workspace";

function money(value: number) { return new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:0 }).format(value); }
function due(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { day:"2-digit", month:"short" }).format(new Date(value)) : "No due date"; }

export function DailySalesWorkspace({ workspace }: { workspace: DailySalesWorkspaceDTO }) {
  const metrics = [{label:"Priority leads",value:workspace.summary.priorityLeads,detail:"High-score accounts",icon:Target},{label:"Follow-ups due",value:workspace.summary.followUpsDue,detail:"Act today",icon:ClockCountdown},{label:"Need first contact",value:workspace.summary.accountsNeedingContact,detail:"Build buying committee",icon:UserPlus},{label:"Pipeline at risk",value:workspace.summary.pipelineAtRisk,detail:"Close date within 30 days",icon:WarningCircle}];
  return <div className="daily-sales-workspace"><section className="sales-day-hero"><div><p>Sales execution</p><h2>Today&apos;s commercial workspace</h2><span>Prioritized account work from verified market intelligence, not generic lead lists.</span></div><Link href="/opportunities" className="button button-primary">Open pipeline <ArrowRight size={17}/></Link></section><section className="sales-day-metrics">{metrics.map(({label,value,detail,icon:Icon})=><article key={label}><span><Icon size={21}/></span><div><small>{label}</small><strong>{value}</strong><em>{detail}</em></div></article>)}</section><div className="sales-day-grid"><section className="sales-day-panel"><header><div><p>Priority queue</p><h3>Accounts to move forward</h3></div><span>{workspace.priorityAccounts.length}</span></header>{workspace.priorityAccounts.length?<div className="priority-account-list">{workspace.priorityAccounts.map((account)=><article key={account.id}><div><span className="priority-score">{account.score}</span><div><strong>{account.companyName}</strong><small>{account.nextTask ?? (account.hasContact ? "Choose a next commercial action" : "Add a procurement or technical contact")}</small><LifecyclePill stage={account.lifecycleStage}/></div></div><div><b>{money(account.pipelineValue)}</b><small>{due(account.dueAt)}</small><Link href={`/accounts/${account.id}#tasks`} aria-label={`Open ${account.companyName}`}>Open <ArrowRight size={14}/></Link></div></article>)}</div>:<p className="panel-empty">No approved accounts are ready for sales action yet.</p>}</section><aside className="sales-day-panel"><header><div><p>Attention required</p><h3>Overdue follow-ups</h3></div><span>{workspace.overdueTasks.length}</span></header>{workspace.overdueTasks.length?<div className="overdue-list">{workspace.overdueTasks.map((task)=><Link href={`/accounts/${task.accountId}#tasks`} key={task.id}><span><Phone size={17}/></span><div><strong>{task.title}</strong><small>{task.companyName} · Due {due(task.dueAt)}</small></div><ArrowRight size={15}/></Link>)}</div>:<p className="panel-empty">No overdue follow-ups. Your sales queue is clear.</p>}</aside></div></div>;
}
